
#include "MVE_STU_WC_EffectSequencePreview.h"
#include "MVE_StageLevel_EffectSequenceManager.h"
#include "MVE.h"
#include "MVE_API_Helper.h"
#include "Components/Button.h"
#include "Components/Slider.h"
#include "Components/TextBlock.h"
#include "Components/Image.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/AudioComponent.h"
#include "Engine/TextureRenderTarget2D.h"
#include "Sound/SoundWave.h"
#include "Kismet/GameplayStatics.h"
#include "glTFRuntimeFunctionLibrary.h"
#include "glTFRuntimeAudioFunctionLibrary.h"

void UMVE_STU_WC_EffectSequencePreview::NativeConstruct()
{
	Super::NativeConstruct();

	bIsSliderDragging = false;
	bIsAudioPaused = false;
	TotalDurationTimeStamp = 0;

	// PlayerController ê°€ì ¸ì˜¤ê¸°
	APlayerController* PC = GetOwningPlayer();
	if (!PC)
	{
		PRINTLOG(TEXT("PlayerControllerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤!"));
		return;
	}

	// AudioComponent ìƒì„± ë° PlayerControllerì— ë¶€ì°©
	AudioComponent = NewObject<UAudioComponent>(PC);
	if (AudioComponent)
	{
		AudioComponent->RegisterComponent();
		AudioComponent->bAutoActivate = false;

		// PlayerControllerì— ë¶€ì°©
		AudioComponent->AttachToComponent(PC->GetRootComponent(), FAttachmentTransformRules::KeepRelativeTransform);

		// UI ì‚¬ìš´ë“œ ì„¤ì • (2D ì‚¬ìš´ë“œ, Attenuation ì—†ìŒ)
		AudioComponent->SetUISound(true);
		AudioComponent->bAllowSpatialization = false;
		AudioComponent->bIsUISound = true;
		AudioComponent->bOverrideAttenuation = true;
		AudioComponent->SetVolumeMultiplier(1.0f);

		// Activate í˜¸ì¶œ
		AudioComponent->Activate();

		// ì¬ìƒ í¼ì„¼íŠ¸ ë¸ë¦¬ê²Œì´íŠ¸ ë°”ì¸ë”©
		AudioComponent->OnAudioPlaybackPercent.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnAudioPlaybackPercentChanged);

		PRINTLOG(TEXT("AudioComponent ìƒì„±ë¨ (PlayerControllerì— ë¶€ì°©, UI Sound ì„¤ì • ì™„ë£Œ)"));
	}

	// ë²„íŠ¼ ì´ë²¤íŠ¸ ë°”ì¸ë”©
	if (PlayButton)
	{
		PlayButton->OnClicked.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnPlayButtonClicked);
	}

	// ìŠ¬ë¼ì´ë” ì´ë²¤íŠ¸ ë°”ì¸ë”©
	if (PlaybackSlider)
	{
		PlaybackSlider->OnMouseCaptureBegin.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnPlaybackSliderMouseCaptureBegin);
		PlaybackSlider->OnMouseCaptureEnd.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnPlaybackSliderMouseCaptureEnd);
		PlaybackSlider->OnValueChanged.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnPlaybackSliderValueChanged);
	}
}

void UMVE_STU_WC_EffectSequencePreview::NativeOnInitialized()
{
	Super::NativeOnInitialized();
}

void UMVE_STU_WC_EffectSequencePreview::NativeDestruct()
{
	Super::NativeDestruct();

	ClearEffectIcons();
}

void UMVE_STU_WC_EffectSequencePreview::SetSequenceData(const TArray<FEffectSequenceData>& SequenceData, int32 TotalDuration)
{
	SequenceDataArray = SequenceData;
	TotalDurationTimeStamp = TotalDuration;

	// ìŠ¬ë¼ì´ë” ë²”ìœ„ ì„¤ì •
	if (PlaybackSlider)
	{
		PlaybackSlider->SetMinValue(0.0f);
		PlaybackSlider->SetMaxValue(static_cast<float>(TotalDuration));
		PlaybackSlider->SetValue(0.0f);
	}

	// ì´ ì‹œê°„ í…ìŠ¤íŠ¸ ì—…ë°ì´íŠ¸
	if (TotalTimeTextBlock)
	{
		TotalTimeTextBlock->SetText(FText::FromString(FormatTime(TotalDuration)));
	}

	// ê¸°ì¡´ ì•„ì´ì½˜ ì œê±° í›„ ìƒˆë¡œ ìƒì„±
	ClearEffectIcons();
	CreateEffectIcons();

	// EffectSequenceManagerì— ë°ì´í„° ì „ë‹¬
	if (EffectSequenceManager)
	{
		EffectSequenceManager->SetSequenceData(SequenceData);
	}

	PRINTLOG(TEXT("Effect Sequence Preview ë°ì´í„° ì„¤ì • ì™„ë£Œ - %dê°œ ì´í™íŠ¸, ì´ ê¸¸ì´: %s"),
		SequenceData.Num(), *FormatTime(TotalDuration));
}

void UMVE_STU_WC_EffectSequencePreview::UpdatePlaybackProgress(int32 CurrentTimeStamp)
{
	// ìŠ¬ë¼ì´ë” ë“œë˜ê·¸ ì¤‘ì´ë©´ ì—…ë°ì´íŠ¸ ë¬´ì‹œ
	if (bIsSliderDragging)
	{
		return;
	}

	// ìŠ¬ë¼ì´ë” ê°’ ì—…ë°ì´íŠ¸
	if (PlaybackSlider)
	{
		PlaybackSlider->SetValue(static_cast<float>(CurrentTimeStamp));
	}

	// í˜„ì¬ ì‹œê°„ í…ìŠ¤íŠ¸ ì—…ë°ì´íŠ¸
	if (CurrentTimeTextBlock)
	{
		CurrentTimeTextBlock->SetText(FText::FromString(FormatTime(CurrentTimeStamp)));
	}
}

void UMVE_STU_WC_EffectSequencePreview::UpdatePlayPauseButton(bool bIsPlaying)
{
	if (PlayStateImage)
	{
		UTexture2D* IconTexture = bIsPlaying ? PauseIconTexture : PlayIconTexture;
		if (IconTexture)
		{
			PlayStateImage->SetBrushFromTexture(IconTexture);
		}
	}
}

void UMVE_STU_WC_EffectSequencePreview::ResetPreview()
{
	// ìŠ¬ë¼ì´ë” ì´ˆê¸°í™”
	if (PlaybackSlider)
	{
		PlaybackSlider->SetValue(0.0f);
	}

	// ì‹œê°„ í…ìŠ¤íŠ¸ ì´ˆê¸°í™”
	if (CurrentTimeTextBlock)
	{
		CurrentTimeTextBlock->SetText(FText::FromString(TEXT("0:00")));
	}

	// AudioComponent ì •ì§€
	if (AudioComponent && AudioComponent->IsPlaying())
	{
		AudioComponent->Stop();
	}

	// EffectSequenceManager ì´ˆê¸°í™”
	if (EffectSequenceManager)
	{
		EffectSequenceManager->ResetSequence();
	}

	PRINTLOG(TEXT("Effect Sequence Preview ì´ˆê¸°í™”"));
}

void UMVE_STU_WC_EffectSequencePreview::SetEffectSequenceManager(AMVE_StageLevel_EffectSequenceManager* Manager)
{
	EffectSequenceManager = Manager;
	PRINTLOG(TEXT("EffectSequenceManager ì„¤ì •ë¨"));
}

void UMVE_STU_WC_EffectSequencePreview::SetRenderTarget(UTextureRenderTarget2D* RenderTarget)
{
	if (StagePreviewImage && RenderTarget)
	{
		// RenderTargetì„ Brushë¡œ ë³€í™˜
		FSlateBrush Brush;
		Brush.SetResourceObject(RenderTarget);
		Brush.ImageSize = FVector2D(RenderTarget->SizeX, RenderTarget->SizeY);
		Brush.DrawAs = ESlateBrushDrawType::Image;

		StagePreviewImage->SetBrush(Brush);

		PRINTLOG(TEXT("StagePreviewImageì— RenderTarget ì„¤ì •ë¨: %s"), *RenderTarget->GetName());
	}
	else
	{
		PRINTLOG(TEXT("StagePreviewImage ë˜ëŠ” RenderTargetì´ nullì…ë‹ˆë‹¤"));
	}
}

void UMVE_STU_WC_EffectSequencePreview::LoadTestData()
{
	// í…ŒìŠ¤íŠ¸ìš© ë”ë¯¸ ë°ì´í„° ìƒì„±
	// AIê°€ ë¶„ì„í•œ ê²°ê³¼ë¥¼ ì‹œë®¬ë ˆì´ì…˜
	TArray<FEffectSequenceData> TestData;

	// 0:10ì´ˆ - Spotlight VerySlowSpeed (ê³ ìš”í•œ ì¸íŠ¸ë¡œ)
	TestData.Add(FEffectSequenceData(100, FGameplayTag::RequestGameplayTag(FName("VFX.Spotlight.VerySlowSpeed"))));

	// 0:30ì´ˆ - Spotlight SlowSpeed (ì„œì •ì ì¸ ì‹œì‘)
	TestData.Add(FEffectSequenceData(300, FGameplayTag::RequestGameplayTag(FName("VFX.Spotlight.SlowSpeed"))));

	// 1:00ë¶„ - Fanfare LowSpawnRate (ì„¤ë ˆëŠ” ì²« ì†Œì ˆ)
	TestData.Add(FEffectSequenceData(600, FGameplayTag::RequestGameplayTag(FName("VFX.Fanfare.LowSpawnRate"))));

	// 1:30ë¶„ - Spotlight NormalSpeed (ê²½ì¾Œí•œ íŒ)
	TestData.Add(FEffectSequenceData(900, FGameplayTag::RequestGameplayTag(FName("VFX.Spotlight.NormalSpeed"))));

	// 2:00ë¶„ - Flame NormalSmallSizeAndNormalSpeed (í™í•© ë¹„íŠ¸)
	TestData.Add(FEffectSequenceData(1200, FGameplayTag::RequestGameplayTag(FName("VFX.Flame.NormalSmallSizeAndNormalSpeed"))));

	// 2:30ë¶„ - Fanfare NormalSpawnRate (ì¦ê±°ìš´ ì¶•ì œ)
	TestData.Add(FEffectSequenceData(1500, FGameplayTag::RequestGameplayTag(FName("VFX.Fanfare.NormalSpawnRate"))));

	// 3:00ë¶„ - Spotlight FastSpeed (ê³ ì¡°ë˜ëŠ” ëŒ„ìŠ¤)
	TestData.Add(FEffectSequenceData(1800, FGameplayTag::RequestGameplayTag(FName("VFX.Spotlight.FastSpeed"))));

	// 3:30ë¶„ - Flame FastSizeAndFastSpeed (íŒŒì›Œí’€í•œ í•˜ì´ë¼ì´íŠ¸)
	TestData.Add(FEffectSequenceData(2100, FGameplayTag::RequestGameplayTag(FName("VFX.Flame.FastSizeAndFastSpeed"))));

	// 4:00ë¶„ - Fanfare HighSpawnRate (í­ë°œì ì¸ ë©”ì¸ í•˜ì´ë¼ì´íŠ¸)
	TestData.Add(FEffectSequenceData(2400, FGameplayTag::RequestGameplayTag(FName("VFX.Fanfare.HighSpawnRate"))));

	// 4:30ë¶„ - Spotlight VeryFastSpeed (ë½ ì¥ë¥´ í´ë¼ì´ë§‰ìŠ¤)
	TestData.Add(FEffectSequenceData(2700, FGameplayTag::RequestGameplayTag(FName("VFX.Spotlight.VeryFastSpeed"))));

	// 5:00ë¶„ - Flame VeryFastSizeAndVeryFastSpeed (ê·¹ê°• í´ë¼ì´ë§‰ìŠ¤)
	TestData.Add(FEffectSequenceData(3000, FGameplayTag::RequestGameplayTag(FName("VFX.Flame.VeryFastSizeAndVeryFastSpeed"))));

	// 5:30ë¶„ - Fanfare VeryHighSpawnRate (ê·¸ëœë“œ í”¼ë‚ ë ˆ)
	TestData.Add(FEffectSequenceData(3300, FGameplayTag::RequestGameplayTag(FName("VFX.Fanfare.VeryHighSpawnRate"))));

	// ì´ ê¸¸ì´ 6ë¶„ (3600 = 360ì´ˆ * 10)
	int32 TotalDuration = 3600;

	// ë°ì´í„° ì„¤ì •
	SetSequenceData(TestData, TotalDuration);

	PRINTLOG(TEXT("í…ŒìŠ¤íŠ¸ ë°ì´í„° ë¡œë“œ ì™„ë£Œ - %dê°œ ì´í™íŠ¸, ì´ ê¸¸ì´: 6:00"), TestData.Num());
}

void UMVE_STU_WC_EffectSequencePreview::SetAudioFile(const FAudioFile& AudioFile)
{
	PRINTLOG(TEXT("ğŸµ ìƒˆ ìŒì•… ì„ íƒ: %s - %s"), *AudioFile.Title, *AudioFile.Artist);

	// ğŸ”¹ UI ë¨¼ì € ì´ˆê¸°í™” (ì–´ë–¤ ê²½ë¡œë¡œ ê°€ë“  ë¬´ì¡°ê±´ ë¦¬ì…‹)
	if (PlaybackSlider)
	{
		PlaybackSlider->SetValue(0.0f);
	}
	if (CurrentTimeTextBlock)
	{
		CurrentTimeTextBlock->SetText(FText::FromString(TEXT("0:00")));
	}

	// ğŸ”¹ ë¸ë¦¬ê²Œì´íŠ¸ ë¨¼ì € í•´ì œ
	if (AudioComponent)
	{
		AudioComponent->OnAudioPlaybackPercent.Clear();
	}

	// ğŸ”¹ ê¸°ì¡´ ì¬ìƒ ì¤‘ì¸ ìŒì•… ì™„ì „íˆ ì •ì§€
	if (AudioComponent)
	{
		if (AudioComponent->IsPlaying())
		{
			AudioComponent->Stop();
			PRINTLOG(TEXT("ê¸°ì¡´ ìŒì•… ì •ì§€ë¨"));
		}
		AudioComponent->SetPaused(false);
		AudioComponent->SetSound(nullptr);
	}

	// EffectSequenceManager ì´ˆê¸°í™”
	if (EffectSequenceManager)
	{
		EffectSequenceManager->ResetSequence();
	}

	// CurrentSound ì´ˆê¸°í™” (ìƒˆë¡œìš´ ê³¡ ë¡œë“œë  ë•Œê¹Œì§€ null)
	CurrentSound = nullptr;
	CurrentAudioFile = AudioFile;
	bIsAudioPaused = false; // ì¼ì‹œì •ì§€ ìƒíƒœ í”Œë˜ê·¸ ë¦¬ì…‹

	// Duration is in seconds, convert to 1/10 second units
	TotalDurationTimeStamp = AudioFile.Duration * 10;

	// ğŸ”¹ UI ì´ˆê¸°í™” (Stop() í›„ì— ì„¤ì •í•˜ì—¬ ë¸ë¦¬ê²Œì´íŠ¸ë¡œ ì¸í•œ ë®ì–´ì“°ê¸° ë°©ì§€)
	if (PlaybackSlider)
	{
		PlaybackSlider->SetMinValue(0.0f);
		PlaybackSlider->SetMaxValue(static_cast<float>(TotalDurationTimeStamp));
		PlaybackSlider->SetValue(0.0f);
	}

	// í˜„ì¬ ì‹œê°„ í…ìŠ¤íŠ¸ ì´ˆê¸°í™”
	if (CurrentTimeTextBlock)
	{
		CurrentTimeTextBlock->SetText(FText::FromString(TEXT("0:00")));
	}

	// ì´ ì‹œê°„ í…ìŠ¤íŠ¸ ì—…ë°ì´íŠ¸
	if (TotalTimeTextBlock)
	{
		TotalTimeTextBlock->SetText(FText::FromString(FormatTime(TotalDurationTimeStamp)));
	}

	// ì¬ìƒ ë²„íŠ¼ ìƒíƒœ ì—…ë°ì´íŠ¸ (ì •ì§€ ìƒíƒœë¡œ)
	UpdatePlayPauseButton(false);

	PRINTLOG(TEXT("ìŒì•… ì„¤ì • ì™„ë£Œ: ê¸¸ì´ %s"), *FormatTime(TotalDurationTimeStamp));

	// ğŸ¯ Asset ìºì‹œ í™•ì¸
	if (CachedAssets.Contains(AudioFile.Id))
	{
		PRINTLOG(TEXT("âœ… ìºì‹œì—ì„œ Asset ë¡œë“œ: %s"), *AudioFile.Title);

		UglTFRuntimeAsset* CachedAsset = CachedAssets[AudioFile.Id];
		if (CachedAsset)
		{
			// ğŸ”¹ ë§¤ë²ˆ ìƒˆë¡œìš´ SoundWave ìƒì„± (ì¬ìƒ ìœ„ì¹˜ ì™„ì „íˆ ë¦¬ì…‹!)
			const EglTFRuntimeAudioDecoder Decoder{};
			const FglTFRuntimeAudioConfig Config{};
			USoundWave* FreshSoundWave = UglTFRuntimeAudioFunctionLibrary::LoadSoundFromBlob(CachedAsset, Decoder, Config);

			if (FreshSoundWave)
			{
				CurrentSound = FreshSoundWave;
				PRINTLOG(TEXT("âœ… ìƒˆ SoundWave ìƒì„± ì™„ë£Œ: %s (Duration: %.2fì´ˆ)"), *AudioFile.Title, FreshSoundWave->Duration);

				// ğŸ”¹ TotalDurationTimeStamp ì—…ë°ì´íŠ¸
				TotalDurationTimeStamp = FMath::RoundToInt(FreshSoundWave->Duration * 10.0f);
				PRINTLOG(TEXT("TotalDurationTimeStamp ì—…ë°ì´íŠ¸: %d (%s)"), TotalDurationTimeStamp, *FormatTime(TotalDurationTimeStamp));

				// ğŸ”¹ ìŠ¬ë¼ì´ë” ë²”ìœ„ ì—…ë°ì´íŠ¸
				if (PlaybackSlider)
				{
					PlaybackSlider->SetMaxValue(static_cast<float>(TotalDurationTimeStamp));
					PlaybackSlider->SetValue(0.0f);
				}

				// ğŸ”¹ í˜„ì¬ ì‹œê°„ í…ìŠ¤íŠ¸ ì´ˆê¸°í™”
				if (CurrentTimeTextBlock)
				{
					CurrentTimeTextBlock->SetText(FText::FromString(TEXT("0:00")));
				}

				// ğŸ”¹ ì´ ì‹œê°„ í…ìŠ¤íŠ¸ ì—…ë°ì´íŠ¸
				if (TotalTimeTextBlock)
				{
					TotalTimeTextBlock->SetText(FText::FromString(FormatTime(TotalDurationTimeStamp)));
				}

				// ğŸ”¹ ë¸ë¦¬ê²Œì´íŠ¸ ë°”ì¸ë”©
				if (AudioComponent)
				{
					AudioComponent->OnAudioPlaybackPercent.Clear();
					AudioComponent->OnAudioPlaybackPercent.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnAudioPlaybackPercentChanged);
				}

				return; // ì„œë²„ ìš”ì²­ ë¶ˆí•„ìš”!
			}
		}
	}

	// ìºì‹œ ë¯¸ìŠ¤ - ì„œë²„ì—ì„œ ë¡œë“œ
	PRINTLOG(TEXT("âŒ ìºì‹œ ë¯¸ìŠ¤ - ì„œë²„ì—ì„œ ìŒì•… ë‹¤ìš´ë¡œë“œ: %s"), *AudioFile.Title);

	// StreamAudio APIë¥¼ í˜¸ì¶œí•˜ì—¬ Presigned URL ë°›ê¸°
	FOnStreamAudioComplete OnResult;
	OnResult.BindLambda([this](const bool bSuccess, const FStreamAudioResponseData& ResponseData, const FString& ErrorCode)
	{
		if (bSuccess)
		{
			const FString PresignedUrl = ResponseData.StreamUrl;
			PRINTLOG(TEXT("Presigned URL ìˆ˜ì‹  ì„±ê³µ: %s"), *PresignedUrl);

			// glTFRuntimeìœ¼ë¡œ URLì—ì„œ ì˜¤ë””ì˜¤ ë‹¤ìš´ë¡œë“œ
			FglTFRuntimeHttpResponse Response;
			Response.BindUFunction(this, FName("OnAudioLoadedFromUrl"));

			const TMap<FString, FString> Headers;
			FglTFRuntimeConfig Config;
			Config.bAsBlob = true; // ë°”ì´ë„ˆë¦¬ ë°ì´í„°(Blob)ë¡œ ë°›ë„ë¡ ì„¤ì •
			UglTFRuntimeFunctionLibrary::glTFLoadAssetFromUrl(PresignedUrl, Headers, Response, Config);
		}
		else
		{
			PRINTLOG(TEXT("Presigned URL ë°›ê¸° ì‹¤íŒ¨: %s"), *ErrorCode);
		}
	});

	UMVE_API_Helper::StreamAudio(AudioFile.Id, OnResult);
}

void UMVE_STU_WC_EffectSequencePreview::OnAudioPlaybackPercentChanged(const USoundWave* PlayingSoundWave, const float PlaybackPercent)
{
	if (!PlayingSoundWave || bIsSliderDragging)
	{
		return;
	}

	// í˜„ì¬ ì¬ìƒ ì‹œê°„ ê³„ì‚° (ì´ˆ ë‹¨ìœ„)
	float PlaybackTime = PlaybackPercent * PlayingSoundWave->Duration;

	// 1/10ì´ˆ ë‹¨ìœ„ë¡œ ë³€í™˜
	int32 CurrentTimeStamp = static_cast<int32>(PlaybackTime * 10.0f);

	// UI ì—…ë°ì´íŠ¸ (ìŠ¬ë¼ì´ë”ëŠ” ë“œë˜ê·¸ ì¤‘ì´ ì•„ë‹ ë•Œë§Œ)
	UpdatePlaybackProgress(CurrentTimeStamp);

	// EffectSequenceManagerì˜ íƒ€ì„ë¼ì¸ì€ ìì²´ì ìœ¼ë¡œ Tickì—ì„œ ì—…ë°ì´íŠ¸ë˜ë¯€ë¡œ
	// ì—¬ê¸°ì„œëŠ” UIë§Œ ë™ê¸°í™”
}

void UMVE_STU_WC_EffectSequencePreview::OnPlayButtonClicked()
{
	PRINTLOG(TEXT("PlayButton í´ë¦­ë¨!"));

	if (!EffectSequenceManager)
	{
		PRINTLOG(TEXT("EffectSequenceManagerê°€ nullì…ë‹ˆë‹¤! SetEffectSequenceManager()ë¥¼ ë¨¼ì € í˜¸ì¶œí•˜ì„¸ìš”."));

		// EffectSequenceManager ì—†ì´ë„ ìŒì•…ë§Œ ì¬ìƒ
		if (AudioComponent && CurrentSound)
		{
			if (bIsAudioPaused)
			{
				AudioComponent->SetPaused(false);
				bIsAudioPaused = false;
				PRINTLOG(TEXT("AudioComponent ì¬ê°œ (EffectSequenceManager ì—†ìŒ)"));
			}
			else if (!AudioComponent->IsPlaying())
			{
				AudioComponent->Stop(); // ì¬ìƒ ìœ„ì¹˜ ë¦¬ì…‹ì„ ìœ„í•´ ëª…ì‹œì ìœ¼ë¡œ Stop í˜¸ì¶œ
				AudioComponent->SetSound(CurrentSound);
				AudioComponent->Play(0.0f); // ëª…ì‹œì ìœ¼ë¡œ 0ì´ˆë¶€í„° ì¬ìƒ
				PRINTLOG(TEXT("AudioComponent ì¬ìƒ ì‹œì‘ (EffectSequenceManager ì—†ìŒ) - 0:00ë¶€í„°"));
				PRINTLOG(TEXT("  - Sound: %s"), CurrentSound ? *CurrentSound->GetName() : TEXT("null"));
				PRINTLOG(TEXT("  - Duration: %.2fì´ˆ"), CurrentSound ? CurrentSound->Duration : 0.0f);
				PRINTLOG(TEXT("  - IsPlaying: %s"), AudioComponent->IsPlaying() ? TEXT("Yes") : TEXT("No"));
				PRINTLOG(TEXT("  - Volume: %.2f"), AudioComponent->VolumeMultiplier);
				PRINTLOG(TEXT("  - bIsUISound: %s"), AudioComponent->bIsUISound ? TEXT("Yes") : TEXT("No"));
			}
			else
			{
				AudioComponent->SetPaused(true);
				bIsAudioPaused = true;
				PRINTLOG(TEXT("AudioComponent ì¼ì‹œì •ì§€ (EffectSequenceManager ì—†ìŒ)"));
			}
		}
		else
		{
			PRINTLOG(TEXT("AudioComponent ë˜ëŠ” CurrentSoundê°€ nullì…ë‹ˆë‹¤!"));
			PRINTLOG(TEXT("AudioComponent: %s, CurrentSound: %s"),
				AudioComponent ? TEXT("ì¡´ì¬") : TEXT("null"),
				CurrentSound ? TEXT("ì¡´ì¬") : TEXT("null"));
		}
		return;
	}

	if (EffectSequenceManager->IsPlaying())
	{
		// ì¤‘ì§€
		EffectSequenceManager->StopSequence();

		// AudioComponent ì¼ì‹œì •ì§€
		if (AudioComponent && AudioComponent->IsPlaying())
		{
			AudioComponent->SetPaused(true);
			bIsAudioPaused = true;
		}

		OnStopClicked.Broadcast();
		PRINTLOG(TEXT("ì¬ìƒ ì¤‘ì§€"));
	}
	else
	{
		// ì¬ìƒ ì‹œì‘
		EffectSequenceManager->StartSequence(false);

		// AudioComponent ì¬ìƒ ë˜ëŠ” ì¬ê°œ
		if (AudioComponent)
		{
			if (CurrentSound)
			{
				if (bIsAudioPaused)
				{
					AudioComponent->SetPaused(false);
					bIsAudioPaused = false;
					PRINTLOG(TEXT("AudioComponent ì¬ê°œ"));
				}
				else if (!AudioComponent->IsPlaying())
				{
					AudioComponent->Stop(); // ì¬ìƒ ìœ„ì¹˜ ë¦¬ì…‹ì„ ìœ„í•´ ëª…ì‹œì ìœ¼ë¡œ Stop í˜¸ì¶œ
					AudioComponent->SetSound(CurrentSound);
					AudioComponent->Play(0.0f); // ëª…ì‹œì ìœ¼ë¡œ 0ì´ˆë¶€í„° ì¬ìƒ
					PRINTLOG(TEXT("AudioComponent ì¬ìƒ ì‹œì‘ - 0:00ë¶€í„°"));
					PRINTLOG(TEXT("  - Sound: %s"), CurrentSound ? *CurrentSound->GetName() : TEXT("null"));
					PRINTLOG(TEXT("  - Duration: %.2fì´ˆ"), CurrentSound ? CurrentSound->Duration : 0.0f);
					PRINTLOG(TEXT("  - IsPlaying: %s"), AudioComponent->IsPlaying() ? TEXT("Yes") : TEXT("No"));
					PRINTLOG(TEXT("  - Volume: %.2f"), AudioComponent->VolumeMultiplier);
					PRINTLOG(TEXT("  - bIsUISound: %s"), AudioComponent->bIsUISound ? TEXT("Yes") : TEXT("No"));
				}
			}
			else
			{
				PRINTLOG(TEXT("ì¬ìƒí•  ìŒì•…ì´ ì„¤ì •ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤. LoadTestData() ë˜ëŠ” SetAudioFile()ì„ ë¨¼ì € í˜¸ì¶œí•˜ì„¸ìš”."));
			}
		}
		else
		{
			PRINTLOG(TEXT("AudioComponentê°€ nullì…ë‹ˆë‹¤!"));
		}

		OnPlayClicked.Broadcast();
		PRINTLOG(TEXT("ì¬ìƒ ì‹œì‘"));
	}

	UpdatePlayPauseButton(EffectSequenceManager->IsPlaying());
}

void UMVE_STU_WC_EffectSequencePreview::OnPlaybackSliderMouseCaptureBegin()
{
	bIsSliderDragging = true;
}

void UMVE_STU_WC_EffectSequencePreview::OnPlaybackSliderMouseCaptureEnd()
{
	bIsSliderDragging = false;

	// ë“œë˜ê·¸ ì¢…ë£Œ ì‹œ EffectSequenceManagerì˜ ì‹œê°„ ì—…ë°ì´íŠ¸
	if (PlaybackSlider && EffectSequenceManager)
	{
		int32 NewTimeStamp = static_cast<int32>(PlaybackSlider->GetValue());
		EffectSequenceManager->SeekToTimeStamp(NewTimeStamp);

		// AudioComponentë„ ê°™ì€ ìœ„ì¹˜ë¡œ ì‹œí¬
		if (AudioComponent && CurrentSound && TotalDurationTimeStamp > 0)
		{
			float SeekTime = static_cast<float>(NewTimeStamp) / 10.0f; // 1/10ì´ˆ â†’ ì´ˆ ë³€í™˜
			AudioComponent->SetFloatParameter(FName("StartTime"), SeekTime);

			// ì¬ìƒ ì¤‘ì´ì—ˆìœ¼ë©´ ë‹¤ì‹œ ì¬ìƒ
			if (EffectSequenceManager->IsPlaying())
			{
				AudioComponent->Stop();
				AudioComponent->SetSound(CurrentSound);
				AudioComponent->Play(SeekTime);
			}
		}

		PRINTLOG(TEXT("ìŠ¬ë¼ì´ë” ë“œë˜ê·¸ ì¢…ë£Œ - TimeStamp: %d"), NewTimeStamp);
	}
}

void UMVE_STU_WC_EffectSequencePreview::OnPlaybackSliderValueChanged(float Value)
{
	// ë“œë˜ê·¸ ì¤‘ì¼ ë•Œë§Œ ì‹œê°„ í…ìŠ¤íŠ¸ ì—…ë°ì´íŠ¸ (EffectSequenceManagerëŠ” ë“œë˜ê·¸ ì¢…ë£Œ ì‹œ ì—…ë°ì´íŠ¸)
	if (bIsSliderDragging && CurrentTimeTextBlock)
	{
		int32 TimeStamp = static_cast<int32>(Value);
		CurrentTimeTextBlock->SetText(FText::FromString(FormatTime(TimeStamp)));
	}
}

void UMVE_STU_WC_EffectSequencePreview::CreateEffectIcons()
{
	if (!IconCanvas || !PlaybackSlider)
	{
		PRINTLOG(TEXT("IconCanvas ë˜ëŠ” PlaybackSliderê°€ ì—†ìŠµë‹ˆë‹¤"));
		return;
	}

	// ìŠ¬ë¼ì´ë”ì˜ ì‹¤ì œ í”½ì…€ ë„ˆë¹„ ê°€ì ¸ì˜¤ê¸°
	FVector2D SliderSize = PlaybackSlider->GetCachedGeometry().GetLocalSize();
	float SliderWidth = SliderSize.X;

	// ìŠ¬ë¼ì´ë”ê°€ ì•„ì§ ë Œë”ë§ë˜ì§€ ì•Šì•„ í¬ê¸°ê°€ 0ì¼ ìˆ˜ ìˆìŒ
	if (SliderWidth <= 0.0f)
	{
		PRINTLOG(TEXT("ìŠ¬ë¼ì´ë” ë„ˆë¹„ê°€ 0ì…ë‹ˆë‹¤. ë‚˜ì¤‘ì— ë‹¤ì‹œ ì‹œë„í•˜ì„¸ìš”."));
		return;
	}

	for (const FEffectSequenceData& Data : SequenceDataArray)
	{
		// TimeStampë¥¼ 0~1 ë²”ìœ„ë¡œ ì •ê·œí™”
		float NormalizedPosition = 0.0f;
		if (TotalDurationTimeStamp > 0)
		{
			NormalizedPosition = static_cast<float>(Data.TimeStamp) / static_cast<float>(TotalDurationTimeStamp);
		}

		// ìŠ¬ë¼ì´ë” ë„ˆë¹„ì— ë”°ë¼ X ì¢Œí‘œ ê³„ì‚°
		float XPosition = NormalizedPosition * SliderWidth;

		// ì•„ì´ì½˜ í…ìŠ¤ì²˜ ê°€ì ¸ì˜¤ê¸°
		UTexture2D* IconTexture = GetIconTextureForTag(Data.AssetID);
		if (!IconTexture)
		{
			PRINTLOG(TEXT("ì•„ì´ì½˜ í…ìŠ¤ì²˜ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤: %s"), *Data.AssetID.ToString());
			continue;
		}

		// Image ìœ„ì ¯ ìƒì„±
		UImage* IconImage = NewObject<UImage>(this);
		if (IconImage)
		{
			IconImage->SetBrushFromTexture(IconTexture);

			// Canvas Panelì— ì¶”ê°€
			UCanvasPanelSlot* IconSlot = IconCanvas->AddChildToCanvas(IconImage);
			if (IconSlot)
			{
				// ìœ„ì¹˜ ì„¤ì • (ìŠ¬ë¼ì´ë” ìœ„ì— ë°°ì¹˜)
				IconSlot->SetPosition(FVector2D(XPosition, 0.0f));
				IconSlot->SetSize(FVector2D(24.0f, 24.0f)); // ì•„ì´ì½˜ í¬ê¸°
				IconSlot->SetAlignment(FVector2D(0.5f, 0.5f)); // ì¤‘ì•™ ì •ë ¬

				// ìƒì„±ëœ ì•„ì´ì½˜ ì €ì¥ (ë‚˜ì¤‘ì— ì •ë¦¬ìš©)
				EffectIconWidgets.Add(IconImage);

				PRINTLOG(TEXT("ì•„ì´ì½˜ ìƒì„± - TimeStamp: %d, X: %.2f, Tag: %s"),
					Data.TimeStamp, XPosition, *Data.AssetID.ToString());
			}
		}
	}

	PRINTLOG(TEXT("ì´ %dê°œ ì•„ì´ì½˜ ìƒì„± ì™„ë£Œ"), EffectIconWidgets.Num());
}

void UMVE_STU_WC_EffectSequencePreview::ClearEffectIcons()
{
	if (IconCanvas)
	{
		for (UImage* IconWidget : EffectIconWidgets)
		{
			if (IconWidget)
			{
				IconCanvas->RemoveChild(IconWidget);
			}
		}
	}

	EffectIconWidgets.Empty();
	PRINTLOG(TEXT("ì•„ì´ì½˜ ì œê±° ì™„ë£Œ"));
}

UTexture2D* UMVE_STU_WC_EffectSequencePreview::GetIconTextureForTag(const FGameplayTag& Tag) const
{
	FString TagString = Tag.ToString();

	if (TagString.StartsWith(TEXT("VFX.Spotlight")))
	{
		return SpotlightIconTexture;
	}
	else if (TagString.StartsWith(TEXT("VFX.Flame")))
	{
		return FlameIconTexture;
	}
	else if (TagString.StartsWith(TEXT("VFX.Fanfare")))
	{
		return FanfareIconTexture;
	}

	return nullptr;
}

FString UMVE_STU_WC_EffectSequencePreview::FormatTime(int32 TimeStamp)
{
	// TimeStampëŠ” 1/10ì´ˆ ë‹¨ìœ„
	int32 TotalSeconds = TimeStamp / 10;
	int32 Minutes = TotalSeconds / 60;
	int32 Seconds = TotalSeconds % 60;

	return FString::Printf(TEXT("%d:%02d"), Minutes, Seconds);
}

void UMVE_STU_WC_EffectSequencePreview::OnAudioLoadedFromUrl(UglTFRuntimeAsset* Asset)
{
	if (!Asset)
	{
		PRINTLOG(TEXT("ì˜¤ë””ì˜¤ ë¡œë“œ ì‹¤íŒ¨: Assetì´ nullì…ë‹ˆë‹¤"));
		return;
	}

	PRINTLOG(TEXT("ì˜¤ë””ì˜¤ ë‹¤ìš´ë¡œë“œ ì™„ë£Œ, SoundWave ìƒì„± ì¤‘..."));

	// ğŸ¯ Assetì„ ìºì‹œì— ì €ì¥ (SoundWaveê°€ ì•„ë‹ˆë¼!)
	if (!CachedAssets.Contains(CurrentAudioFile.Id))
	{
		CachedAssets.Add(CurrentAudioFile.Id, Asset);
		PRINTLOG(TEXT("ğŸ’¾ ìºì‹œì— Asset ì €ì¥: %s (ID: %d, ì´ ìºì‹œ: %dê³¡)"),
			*CurrentAudioFile.Title, CurrentAudioFile.Id, CachedAssets.Num());
	}

	// ë‹¤ìš´ë¡œë“œëœ ë°”ì´ë„ˆë¦¬ ë°ì´í„°ë¥¼ SoundWaveë¡œ ë³€í™˜
	const EglTFRuntimeAudioDecoder Decoder{};
	const FglTFRuntimeAudioConfig Config{};
	USoundWave* LoadedSoundWave = UglTFRuntimeAudioFunctionLibrary::LoadSoundFromBlob(Asset, Decoder, Config);

	if (LoadedSoundWave)
	{
		CurrentSound = LoadedSoundWave;
		PRINTLOG(TEXT("ìŒì•… ë¡œë“œ ì„±ê³µ: %s (Duration: %.2fì´ˆ)"), *CurrentAudioFile.Title, LoadedSoundWave->Duration);

		// ğŸ”¹ TotalDurationTimeStamp ì—…ë°ì´íŠ¸ (ì‹¤ì œ ë¡œë“œëœ ìŒì•… ê¸¸ì´ ì‚¬ìš©)
		TotalDurationTimeStamp = FMath::RoundToInt(LoadedSoundWave->Duration * 10.0f);
		PRINTLOG(TEXT("TotalDurationTimeStamp ì—…ë°ì´íŠ¸: %d (%s)"), TotalDurationTimeStamp, *FormatTime(TotalDurationTimeStamp));

		// ğŸ”¹ ìŠ¬ë¼ì´ë” ë²”ìœ„ ì—…ë°ì´íŠ¸
		if (PlaybackSlider)
		{
			PlaybackSlider->SetMaxValue(static_cast<float>(TotalDurationTimeStamp));
			PlaybackSlider->SetValue(0.0f);
			PRINTLOG(TEXT("ìŠ¬ë¼ì´ë” ë²”ìœ„ ì—…ë°ì´íŠ¸: 0 ~ %d"), TotalDurationTimeStamp);
		}

		// ğŸ”¹ ì´ ì‹œê°„ í…ìŠ¤íŠ¸ ì—…ë°ì´íŠ¸
		if (TotalTimeTextBlock)
		{
			TotalTimeTextBlock->SetText(FText::FromString(FormatTime(TotalDurationTimeStamp)));
		}

		// AudioComponentì˜ ë¸ë¦¬ê²Œì´íŠ¸ ë°”ì¸ë”©
		if (AudioComponent)
		{
			AudioComponent->OnAudioPlaybackPercent.Clear();
			AudioComponent->OnAudioPlaybackPercent.AddDynamic(this, &UMVE_STU_WC_EffectSequencePreview::OnAudioPlaybackPercentChanged);
			PRINTLOG(TEXT("AudioComponent ë¸ë¦¬ê²Œì´íŠ¸ ë°”ì¸ë”© ì™„ë£Œ"));
		}
	}
	else
	{
		PRINTLOG(TEXT("SoundWave ìƒì„± ì‹¤íŒ¨"));
	}
}
