
#include "../Public/MVE_STU_WidgetController_StudioConcert.h"
#include "MVE.h"
#include "MVE_API_Helper.h"
#include "../Public/MVE_STD_WC_AudioPlayer.h"
#include "../Public/MVE_STD_WC_AudioSearch.h"
#include "StageLevel/Default/Public/MVE_GM_StageLevel.h"
#include "STT/Public/STTSubsystem.h"
#include "UI/Widget/Studio/Public/MVE_STD_WC_AudioSearchResult.h"


void UMVE_STU_WidgetController_StudioConcert::Initialize(UMVE_STD_WC_AudioPlayer* InPlayerWidget, UMVE_STD_WC_AudioSearch* InAudioSearch)
{
    PlayerWidget = InPlayerWidget;
    AudioSearch = InAudioSearch;

    if (!PlayerWidget)
    {
        PRINTNETLOG(this, TEXT("Failed to initialize AudioController: PlayerWidget is null"));
    }

    if (!AudioSearch)
    {
        PRINTNETLOG(this, TEXT("Failed to initialize AudioController: AudioSearch is null"));
    }

    if (USTTSubsystem* STTSubsystem = GetWorld()->GetGameInstance()->GetSubsystem<USTTSubsystem>())
    {
        STTSubsystem->OnSTTCommandReceived.AddDynamic(this, &UMVE_STU_WidgetController_StudioConcert::HandleVoiceCommand);
        PRINTNETLOG(this, TEXT("STT ìŒì„± ëª…ë ¹ ë°”ì¸ë”© ì™„ë£Œ"));
    }
}

void UMVE_STU_WidgetController_StudioConcert::OnTrackSelected(const FMVE_STD_AudioSearchResultData& AudioData)
{
    PRINTNETLOG(this, TEXT("Track selected: %s"), *AudioData.Title);
    
    // í˜„ì¬ íŠ¸ë™ ì •ë³´ ì €ì¥
    CurrentTrackData = AudioData;
    
    // Player UI ì„¤ì •
    SetupPlayerUI(AudioData);
    
    // Presigned URL ë¡œë“œ ë° ë¸Œë¡œë“œìºìŠ¤íŠ¸
    LoadPresignedUrlAndBroadcast(AudioData);
}

void UMVE_STU_WidgetController_StudioConcert::OnPlayRequested()
{
    PRINTNETLOG(this, TEXT("Play requested for track: %s"), *CurrentTrackData.Title);
    SendPlayCommandToClients();
}

void UMVE_STU_WidgetController_StudioConcert::OnStopRequested()
{
    PRINTNETLOG(this, TEXT("Stop requested"));
    SendStopCommandToClients();
}

void UMVE_STU_WidgetController_StudioConcert::SetCurrentTrackData(const FMVE_STD_AudioSearchResultData& Data)
{
    CurrentTrackData = Data;
}

void UMVE_STU_WidgetController_StudioConcert::LoadPresignedUrlAndBroadcast(const FMVE_STD_AudioSearchResultData& AudioData)
{
    PRINTNETLOG(this, TEXT("Requesting Presigned URL for Title: %s"), *AudioData.Title);

    FOnStreamAudioComplete OnResult;
    OnResult.BindLambda([this](const bool bSuccess, const FStreamAudioResponseData& ResponseData, const FString& ErrorCode)
    {
        if (bSuccess)
        {
            const FString PresignedUrl = ResponseData.StreamUrl;
            PRINTNETLOG(this, TEXT("Got PresignedUrl = {%s}, sending to all clients"), *PresignedUrl);

            // GameModeë¥¼ í†µí•´ ëª¨ë“  í´ë¼ì´ì–¸íŠ¸ì— URL ì „ì†¡
            if (UWorld* World = GetWorld())
            {
                if (AMVE_GM_StageLevel* GameMode = World->GetAuthGameMode<AMVE_GM_StageLevel>())
                {
                    GameMode->SendPresignedUrlToAllClients(PresignedUrl);

                    // ğŸ”¥ ìë™ ì¬ìƒ í”Œë˜ê·¸ê°€ ì„¤ì •ë˜ì–´ ìˆìœ¼ë©´ ì¬ìƒ ëª…ë ¹ ì „ì†¡
                    if (bAutoPlayAfterSelection)
                    {
                        PRINTNETLOG(this, TEXT("ğŸµ ìë™ ì¬ìƒ: URL ë¡œë“œ ì™„ë£Œ, ì¬ìƒ ëª…ë ¹ ì „ì†¡"));
                        bAutoPlayAfterSelection = false; // í”Œë˜ê·¸ ë¦¬ì…‹
                        SendPlayCommandToClients();
                    }
                }
                else
                {
                    PRINTNETLOG(this, TEXT("Failed to get AMVE_API_GMTest GameMode"));
                }
            }
        }
        else
        {
            PRINTNETLOG(this, TEXT("Failed to get Presigned URL. Error: %s"), *ErrorCode);
            bAutoPlayAfterSelection = false; // ì‹¤íŒ¨ ì‹œ í”Œë˜ê·¸ ë¦¬ì…‹
        }
    });

    UMVE_API_Helper::StreamAudio(AudioData.Id, OnResult);
}

void UMVE_STU_WidgetController_StudioConcert::SendPlayCommandToClients()
{
    PRINTNETLOG(this, TEXT("Sending play command to all clients"));
    
    if (UWorld* World = GetWorld())
    {
        if (AMVE_GM_StageLevel* GameMode = World->GetAuthGameMode<AMVE_GM_StageLevel>())
        {
            GameMode->SendPlayCommandToAllClients();
        }
        else
        {
            PRINTNETLOG(this, TEXT("Failed to get AMVE_API_GMTest GameMode"));
        }
    }
}

void UMVE_STU_WidgetController_StudioConcert::SendStopCommandToClients()
{
    PRINTNETLOG(this, TEXT("Sending stop command to all clients"));
    
    if (UWorld* World = GetWorld())
    {
        if (AMVE_GM_StageLevel* GameMode = World->GetAuthGameMode<AMVE_GM_StageLevel>())
        {
            GameMode->SendStopCommandToAllClients();
        }
        else
        {
            PRINTNETLOG(this, TEXT("Failed to get AMVE_API_GMTest GameMode"));
        }
    }
}

void UMVE_STU_WidgetController_StudioConcert::SetupPlayerUI(const FMVE_STD_AudioSearchResultData& AudioData)
{
    if (!PlayerWidget)
    {
        PRINTNETLOG(this, TEXT("Cannot setup Player UI: PlayerWidget is null"));
        return;
    }
    
    // AudioPlayerì— ë°ì´í„° ì„¤ì •
    PlayerWidget->SetAudioData(AudioData);
    
    // ë¸ë¦¬ê²Œì´íŠ¸ ì´ˆê¸°í™” ë° ì¬ë“±ë¡
    PlayerWidget->OnPlayClicked.Clear();
    PlayerWidget->OnPlayClicked.AddDynamic(this, &UMVE_STU_WidgetController_StudioConcert::OnPlayRequested);
    
    PlayerWidget->OnStopClicked.Clear();
    PlayerWidget->OnStopClicked.AddDynamic(this, &UMVE_STU_WidgetController_StudioConcert::OnStopRequested);
    
    // UI ì´ˆê¸°í™”
    PlayerWidget->ResetPlaybackUI();
    PlayerWidget->UpdatePlayPauseButton(false); // Paused state
}

int32 UMVE_STU_WidgetController_StudioConcert::FindTrackIndex(const FMVE_STD_AudioSearchResultData& TrackData) const
{
    if (!AudioSearch || AudioSearch->SearchResultWidgets.Num() == 0)
    {
        return -1;
    }

    // Idë¡œ ë¹„êµí•´ì„œ í˜„ì¬ íŠ¸ë™ ì°¾ê¸°
    for (int32 i = 0; i < AudioSearch->SearchResultWidgets.Num(); i++)
    {
        if (AudioSearch->SearchResultWidgets[i])
        {
            FMVE_STD_AudioSearchResultData Data = AudioSearch->SearchResultWidgets[i]->GetAudioData();
            if (Data.Id == TrackData.Id)
            {
                return i;  // ì°¾ì•˜ìŒ!
            }
        }
    }

    return -1;  // ëª» ì°¾ìŒ
}

void UMVE_STU_WidgetController_StudioConcert::OnNextTrackRequested(bool bAutoPlay)
{
    PRINTNETLOG(this, TEXT("â­ï¸ ë‹¤ìŒ ê³¡ ìš”ì²­"));

    // 1. ê²€ìƒ‰ ê²°ê³¼ ìœ íš¨ì„± ì²´í¬
    if (!AudioSearch || AudioSearch->SearchResultWidgets.Num() == 0)
    {
        PRINTNETLOG(this, TEXT("âŒ ì¬ìƒ ëª©ë¡ì´ ë¹„ì–´ìˆìŠµë‹ˆë‹¤."));
        return;
    }

    // 2. í˜„ì¬ íŠ¸ë™ ì¸ë±ìŠ¤ ì°¾ê¸°
    int32 CurrentIndex = FindTrackIndex(CurrentTrackData);

    // 3. í˜„ì¬ íŠ¸ë™ì„ ëª» ì°¾ì•˜ìœ¼ë©´ ì²« ë²ˆì§¸ íŠ¸ë™ ì„ íƒ
    if (CurrentIndex == -1)
    {
        PRINTNETLOG(this, TEXT("âš ï¸ í˜„ì¬ íŠ¸ë™ì„ ì°¾ì„ ìˆ˜ ì—†ìŒ. ì²« ë²ˆì§¸ íŠ¸ë™ ì„ íƒ"));
        CurrentIndex = -1;  // ë‹¤ìŒ ê³„ì‚°ì—ì„œ 0ì´ ë¨
    }

    // 4. ë‹¤ìŒ ì¸ë±ìŠ¤ ê³„ì‚°
    int32 NextIndex = CurrentIndex + 1;
    int32 TotalTracks = AudioSearch->SearchResultWidgets.Num();

    // 5. ê²½ê³„ ì²´í¬ (ìˆœí™˜ ì¬ìƒ)
    if (NextIndex >= TotalTracks)
    {
        PRINTNETLOG(this, TEXT("ğŸ” ë§ˆì§€ë§‰ ê³¡. ì²« ë²ˆì§¸ ê³¡ìœ¼ë¡œ ìˆœí™˜"));
        NextIndex = 0;
    }

    // 6. ë‹¤ìŒ íŠ¸ë™ ê°€ì ¸ì˜¤ê¸°
    UMVE_STD_WC_AudioSearchResult* NextTrackWidget = AudioSearch->SearchResultWidgets[NextIndex];
    if (!NextTrackWidget)
    {
        PRINTNETLOG(this, TEXT("âŒ ë‹¤ìŒ íŠ¸ë™ ìœ„ì ¯ì´ nullì…ë‹ˆë‹¤."));
        return;
    }

    FMVE_STD_AudioSearchResultData NextTrackData = NextTrackWidget->GetAudioData();
    PRINTNETLOG(this, TEXT("âœ… ë‹¤ìŒ ê³¡: %s (ì¸ë±ìŠ¤: %d/%d)"), *NextTrackData.Title, NextIndex + 1, TotalTracks);

    // 7. ìë™ ì¬ìƒ í”Œë˜ê·¸ ì„¤ì •
    if (bAutoPlay)
    {
        bAutoPlayAfterSelection = true;
    }

    // 8. íŠ¸ë™ ì„ íƒ (ê¸°ì¡´ í•¨ìˆ˜ ì¬ì‚¬ìš©!)
    OnTrackSelected(NextTrackData);
}

void UMVE_STU_WidgetController_StudioConcert::OnPreviousTrackRequested(bool bAutoPlay)
{
    PRINTNETLOG(this, TEXT("â®ï¸ ì´ì „ ê³¡ ìš”ì²­"));

    // 1. ê²€ìƒ‰ ê²°ê³¼ ìœ íš¨ì„± ì²´í¬
    if (!AudioSearch || AudioSearch->SearchResultWidgets.Num() == 0)
    {
        PRINTNETLOG(this, TEXT("âŒ ì¬ìƒ ëª©ë¡ì´ ë¹„ì–´ìˆìŠµë‹ˆë‹¤."));
        return;
    }

    // 2. í˜„ì¬ íŠ¸ë™ ì¸ë±ìŠ¤ ì°¾ê¸°
    int32 CurrentIndex = FindTrackIndex(CurrentTrackData);

    // 3. í˜„ì¬ íŠ¸ë™ì„ ëª» ì°¾ì•˜ìœ¼ë©´ ì²« ë²ˆì§¸ íŠ¸ë™ ì„ íƒ
    if (CurrentIndex == -1)
    {
        PRINTNETLOG(this, TEXT("âš ï¸ í˜„ì¬ íŠ¸ë™ì„ ì°¾ì„ ìˆ˜ ì—†ìŒ. ì²« ë²ˆì§¸ íŠ¸ë™ ì„ íƒ"));
        CurrentIndex = 0;
    }

    // 4. ì´ì „ ì¸ë±ìŠ¤ ê³„ì‚°
    int32 PrevIndex = CurrentIndex - 1;
    int32 TotalTracks = AudioSearch->SearchResultWidgets.Num();

    // 5. ê²½ê³„ ì²´í¬ (ì—­ìˆœí™˜)
    if (PrevIndex < 0)
    {
        PRINTNETLOG(this, TEXT("ğŸ” ì²« ë²ˆì§¸ ê³¡. ë§ˆì§€ë§‰ ê³¡ìœ¼ë¡œ ìˆœí™˜"));
        PrevIndex = TotalTracks - 1;
    }

    // 6. ì´ì „ íŠ¸ë™ ê°€ì ¸ì˜¤ê¸°
    UMVE_STD_WC_AudioSearchResult* PrevTrackWidget = AudioSearch->SearchResultWidgets[PrevIndex];
    if (!PrevTrackWidget)
    {
        PRINTNETLOG(this, TEXT("âŒ ì´ì „ íŠ¸ë™ ìœ„ì ¯ì´ nullì…ë‹ˆë‹¤."));
        return;
    }

    FMVE_STD_AudioSearchResultData PrevTrackData = PrevTrackWidget->GetAudioData();
    PRINTNETLOG(this, TEXT("âœ… ì´ì „ ê³¡: %s (ì¸ë±ìŠ¤: %d/%d)"), *PrevTrackData.Title, PrevIndex + 1, TotalTracks);

    // 7. ìë™ ì¬ìƒ í”Œë˜ê·¸ ì„¤ì •
    if (bAutoPlay)
    {
        bAutoPlayAfterSelection = true;
    }

    // 8. íŠ¸ë™ ì„ íƒ (ê¸°ì¡´ í•¨ìˆ˜ ì¬ì‚¬ìš©!)
    OnTrackSelected(PrevTrackData);
}

void UMVE_STU_WidgetController_StudioConcert::HandleVoiceCommand(ESTTCommandType CommandType,
    const FString& OriginalText)
{
    PRINTNETLOG(this, TEXT("ğŸ¤ ìŒì„± ëª…ë ¹ ìˆ˜ì‹ : %s - \"%s\""),
        *USTTSubsystem::GetCommandDisplayName(CommandType),
        *OriginalText);

    switch (CommandType)
    {
    case ESTTCommandType::PlayTrack:
        {
            // í˜„ì¬ íŠ¸ë™ì´ ì„ íƒë˜ì§€ ì•Šì•˜ëŠ”ì§€ ì²´í¬ (Idê°€ 0ì´ë©´ ë¹„ì–´ìˆìŒ)
            if (CurrentTrackData.Id == 0)
            {
                PRINTNETLOG(this, TEXT("âš ï¸ ì„ íƒëœ íŠ¸ë™ì´ ì—†ìŒ. ì²« ë²ˆì§¸ íŠ¸ë™ ìë™ ì„ íƒ ì‹œë„..."));

                // AudioSearchê°€ ìœ íš¨í•˜ê³  ê²€ìƒ‰ ê²°ê³¼ê°€ ìˆëŠ”ì§€ í™•ì¸
                if (AudioSearch && AudioSearch->SearchResultWidgets.Num() > 0)
                {
                    // ì²« ë²ˆì§¸ íŠ¸ë™ ê°€ì ¸ì˜¤ê¸°
                    UMVE_STD_WC_AudioSearchResult* FirstTrack = AudioSearch->SearchResultWidgets[0];
                    if (FirstTrack)
                    {
                        FMVE_STD_AudioSearchResultData FirstTrackData = FirstTrack->GetAudioData();
                        PRINTNETLOG(this, TEXT("âœ… ì²« ë²ˆì§¸ íŠ¸ë™ ì„ íƒ: %s"), *FirstTrackData.Title);

                        // ìë™ ì¬ìƒ í”Œë˜ê·¸ ì„¤ì •
                        bAutoPlayAfterSelection = true;

                        // íŠ¸ë™ ì„ íƒ (URL ìš”ì²­ ë° UI ì„¤ì •)
                        OnTrackSelected(FirstTrackData);
                    }
                    else
                    {
                        PRINTNETLOG(this, TEXT("âŒ ì²« ë²ˆì§¸ íŠ¸ë™ ìœ„ì ¯ì´ nullì…ë‹ˆë‹¤."));
                    }
                }
                else
                {
                    PRINTNETLOG(this, TEXT("âŒ ê²€ìƒ‰ ê²°ê³¼ê°€ ì—†ìŠµë‹ˆë‹¤. ë¨¼ì € ìŒì•… ëª©ë¡ì„ ë¶ˆëŸ¬ì˜¤ì„¸ìš”."));
                }
            }
            else
            {
                // ì´ë¯¸ íŠ¸ë™ì´ ì„ íƒë˜ì–´ ìˆìœ¼ë©´ ë°”ë¡œ ì¬ìƒ
                PRINTNETLOG(this, TEXT("â–¶ï¸ ì„ íƒëœ íŠ¸ë™ ì¬ìƒ: %s"), *CurrentTrackData.Title);
                OnPlayRequested();
            }
        }
        break;

    case ESTTCommandType::StopTrack:
        PRINTNETLOG(this, TEXT("â¹ï¸ Stop ëª…ë ¹ ì‹¤í–‰"));
        OnStopRequested();
        break;

    case ESTTCommandType::NextTrack:
        PRINTNETLOG(this, TEXT("â­ï¸ NextTrack ëª…ë ¹ ì‹¤í–‰"));
        OnNextTrackRequested(true);  // ìë™ ì¬ìƒ
        break;

    default:
        PRINTNETLOG(this, TEXT("âš ï¸ ì²˜ë¦¬ë˜ì§€ ì•Šì€ ëª…ë ¹: %d"), (int32)CommandType);
        break;
    }
}
