
#include "GLBRetargetTestActor.h"

#include "glTFRuntimeAsset.h"
#include "glTFRuntimeFunctionLibrary.h"
#include "MVE.h"
#include "Retargeter/IKRetargetProcessor.h"
#include "Retargeter/IKRetargetProfile.h"

AGLBRetargetTestActor::AGLBRetargetTestActor()
{
	PrimaryActorTick.bCanEverTick = true;

	// ì†ŒìŠ¤ ì»´í¬ë„ŒíŠ¸ (Mannequin)
	SourceMeshComponent = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("SourceMesh"));
	RootComponent = SourceMeshComponent;
    
	// íƒ€ê²Ÿ ì»´í¬ë„ŒíŠ¸ (GLB ë¡œë“œìš©)
	TargetMeshComponent = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("TargetMesh"));
	TargetMeshComponent->SetupAttachment(RootComponent);
	TargetMeshComponent->SetRelativeLocation(FVector(0, 200, 0)); // ì˜†ì— ë°°ì¹˜
}

void AGLBRetargetTestActor::BeginPlay()
{
	Super::BeginPlay();

	PRINTLOG(TEXT("=== GLB Runtime Retargeting System Starting ==="));
    
	// 1. ì†ŒìŠ¤ ë©”ì‹œ ì„¤ì • (Mannequin)
	if (SourceSkeletalMesh)
	{
		SourceMeshComponent->SetSkeletalMesh(SourceSkeletalMesh);
		PRINTLOG(TEXT("âœ… Source mesh (Mannequin) set"));
        
		// ì†ŒìŠ¤ ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ (í…ŒìŠ¤íŠ¸ìš©)
		if (SourceAnimation)
		{
			SourceMeshComponent->PlayAnimation(SourceAnimation, true);
			PRINTLOG(TEXT("âœ… Source animation playing"));
		}
	}
	else
	{
		PRINTLOG(TEXT("âš ï¸ Source mesh not set! Please assign in editor"));
	}
    
	// 2. ë™ì  ë¦¬íƒ€ê²ŒíŒ… ì„¤ì •
	if (SetupDynamicRetargeting())
	{
		PRINTLOG(TEXT("âœ… Dynamic retargeting setup complete!"));
        
		// 3. íƒ€ê²Ÿì„ ì†ŒìŠ¤ì˜ ìì‹ìœ¼ë¡œ ì„¤ì • (AnimBPë¥¼ ìœ„í•´)
		TargetMeshComponent->AttachToComponent(SourceMeshComponent, 
			FAttachmentTransformRules::KeepRelativeTransform);
        
		// 4. AnimBP ì—…ë°ì´íŠ¸
		if (UAnimInstance* AnimInst = TargetMeshComponent->GetAnimInstance())
		{
			AnimInst->UpdateAnimation(0.0f, false);
			PRINTLOG(TEXT("âœ… Target AnimBP updated"));
		}
	}
	else
	{
		PRINTLOG(TEXT("âŒ Failed to setup dynamic retargeting"));
	}
}

void AGLBRetargetTestActor::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	// GC ë³´í˜¸ í•´ì œ
	if (LoadedTargetMesh && LoadedTargetMesh->IsRooted())
	{
		LoadedTargetMesh->RemoveFromRoot();
		PRINTLOG(TEXT("ğŸ§¹ Cleaned up loaded mesh from GC protection"));
	}
	
	Super::EndPlay(EndPlayReason);
}

USkeletalMesh* AGLBRetargetTestActor::LoadGLBFile(const FString& FilePath)
{
	FString ContentDir = FPaths::ProjectContentDir();
	FString FullPath = FPaths::Combine(ContentDir, FilePath);
    
	PRINTLOG(TEXT("ğŸ“ Loading GLB from: %s"), *FullPath);
    
	if (!FPaths::FileExists(FullPath))
	{
		PRINTLOG(TEXT("âŒ File not found: %s"), *FullPath);
		return nullptr;
	}
    
	// glTF Asset ë¡œë“œ
	UglTFRuntimeAsset* Asset = UglTFRuntimeFunctionLibrary::glTFLoadAssetFromFilename(
		FullPath, false, FglTFRuntimeConfig()
	);
    
	if (!Asset)
	{
		PRINTLOG(TEXT("âŒ Failed to load glTF asset"));
		return nullptr;
	}
    
	// SkeletalMesh ì„¤ì •
	FglTFRuntimeSkeletalMeshConfig SkeletalMeshConfig;
	SkeletalMeshConfig.bOverwriteRefSkeleton = true;
	SkeletalMeshConfig.MorphTargetsDuplicateStrategy = 
		EglTFRuntimeMorphTargetsDuplicateStrategy::Merge;
    
	// SkeletalMesh ìƒì„±
	USkeletalMesh* LoadedMesh = Asset->LoadSkeletalMesh(0, 0, SkeletalMeshConfig);
    
	if (LoadedMesh)
	{
		LoadedMesh->AddToRoot(); // GC ë°©ì§€
		PRINTLOG(TEXT("âœ… GLB mesh loaded successfully"));
		return LoadedMesh;
	}
    
	PRINTLOG(TEXT("âŒ Failed to create skeletal mesh from GLB"));
	return nullptr;
}

bool AGLBRetargetTestActor::SetupDynamicRetargeting()
{
	// 1. GLB íŒŒì¼ ë¡œë“œ
	LoadedTargetMesh = LoadGLBFile(GLBFilePath);
	if (!LoadedTargetMesh)
		return false;
    
	// 2. íƒ€ê²Ÿ ë©”ì‹œ ì„¤ì •
	TargetMeshComponent->SetSkeletalMesh(LoadedTargetMesh);
    
	// 3. âœ… ë¯¸ë¦¬ ë§Œë“  íƒ€ê²Ÿ IK Rig ì‚¬ìš© (ë²”ìš© Humanoid IK Rig)
	if (!TargetIKRig)
	{
		PRINTLOG(TEXT("âŒ Target IK Rig not set! Please assign a generic humanoid IK Rig"));
		return false;
	}
    
	// 4. âœ… ë¯¸ë¦¬ ë§Œë“  Retargeter ì‚¬ìš©
	if (!RetargeterAsset)
	{
		PRINTLOG(TEXT("âŒ Retargeter asset not set!"));
		return false;
	}
    
	// 5. IK Retarget Processor ì´ˆê¸°í™”
	RetargetProcessor = NewObject<UIKRetargetProcessor>();
    
	FRetargetProfile Profile;
	RetargetProcessor->Initialize(
		SourceMeshComponent->GetSkeletalMeshAsset(),
		LoadedTargetMesh,  // ëŸ°íƒ€ì„ ë¡œë“œëœ ë©”ì‹œ
		RetargeterAsset,   // ë¯¸ë¦¬ ë§Œë“  Retargeter
		Profile
	);
    
	// 6. AnimBP ì„¤ì •
	if (TargetAnimBPClass)
	{
		TargetMeshComponent->SetAnimInstanceClass(TargetAnimBPClass);
	}
    
	return true;
}


void AGLBRetargetTestActor::PrintBoneStructure(USkeletalMesh* Mesh, const FString& MeshName)
{
	if (!Mesh)
		return;
        
	const FReferenceSkeleton& RefSkeleton = Mesh->GetRefSkeleton();
	PRINTLOG(TEXT("=== %s Bone Structure ==="), *MeshName);
	PRINTLOG(TEXT("Total Bones: %d"), RefSkeleton.GetNum());
    
	// ì²˜ìŒ 10ê°œ ë³¸ë§Œ ì¶œë ¥ (ê°„ê²°í•˜ê²Œ)
	int32 MaxBones = FMath::Min(10, RefSkeleton.GetNum());
	for (int32 i = 0; i < MaxBones; i++)
	{
		FName BoneName = RefSkeleton.GetBoneName(i);
		int32 ParentIndex = RefSkeleton.GetParentIndex(i);
		PRINTLOG(TEXT("  [%d] %s (Parent: %d)"), i, *BoneName.ToString(), ParentIndex);
	}
    
	if (RefSkeleton.GetNum() > 10)
	{
		PRINTLOG(TEXT("  ... and %d more bones"), RefSkeleton.GetNum() - 10);
	}
}
