// Fill out your copyright notice in the Description page of Project Settings.

#include "MVE_StageLevel_EffectSequenceManager.h"
#include "MVE_StageLevel_SpotlightManager.h"
#include "MVE_StageLevel_FlameManager.h"
#include "MVE_StageLevel_FanfareManager.h"
#include "MVE.h"
#include "Kismet/GameplayStatics.h"

AMVE_StageLevel_EffectSequenceManager::AMVE_StageLevel_EffectSequenceManager()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.TickInterval = 0.0f; // ë§¤ í”„ë ˆì„ Tick

	CurrentTimeStamp = 0;
	NextEffectIndex = 0;
	bIsPlaying = false;
	AccumulatedTime = 0.0f;
	SpotlightManager = nullptr;
	FlameManager = nullptr;
	FanfareManager = nullptr;
}

void AMVE_StageLevel_EffectSequenceManager::BeginPlay()
{
	Super::BeginPlay();

	FindManagers();
}

void AMVE_StageLevel_EffectSequenceManager::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (bIsPlaying)
	{
		UpdateTimeline(DeltaTime);
	}
}

void AMVE_StageLevel_EffectSequenceManager::SetSequenceData(const TArray<FEffectSequenceData>& SequenceData)
{
	EffectSequenceDataArray = SequenceData;

	// TimeStamp ê¸°ì¤€ìœ¼ë¡œ ì •ë ¬ (ì˜¤ë¦„ì°¨ìˆœ)
	EffectSequenceDataArray.Sort([](const FEffectSequenceData& A, const FEffectSequenceData& B)
	{
		return A.TimeStamp < B.TimeStamp;
	});

	ResetSequence();

	PRINTLOG(TEXT("Effect Sequence Data ë“±ë¡ ì™„ë£Œ: %dê°œ"), EffectSequenceDataArray.Num());
}

void AMVE_StageLevel_EffectSequenceManager::StartSequence(bool bFromBeginning)
{
	if (bFromBeginning)
	{
		ResetSequence();
	}

	bIsPlaying = true;
	AccumulatedTime = 0.0f;

	PRINTLOG(TEXT("Effect Sequence ì‹œì‘ - TimeStamp: %d"), CurrentTimeStamp);
}

void AMVE_StageLevel_EffectSequenceManager::StopSequence()
{
	bIsPlaying = false;

	PRINTLOG(TEXT("Effect Sequence ì¤‘ì§€ - TimeStamp: %d"), CurrentTimeStamp);
}

void AMVE_StageLevel_EffectSequenceManager::ResetSequence()
{
	CurrentTimeStamp = 0;
	NextEffectIndex = 0;
	AccumulatedTime = 0.0f;

	PRINTLOG(TEXT("Effect Sequence ì´ˆê¸°í™”"));
}

void AMVE_StageLevel_EffectSequenceManager::SeekToTimeStamp(int32 TimeStamp)
{
	CurrentTimeStamp = TimeStamp;
	AccumulatedTime = 0.0f;

	// NextEffectIndex ì¬ê³„ì‚°: TimeStampë³´ë‹¤ í° ì²« ë²ˆì§¸ ì¸ë±ìŠ¤ ì°¾ê¸°
	NextEffectIndex = 0;
	for (int32 i = 0; i < EffectSequenceDataArray.Num(); ++i)
	{
		if (EffectSequenceDataArray[i].TimeStamp > CurrentTimeStamp)
		{
			NextEffectIndex = i;
			break;
		}
		NextEffectIndex = i + 1; // ë§ˆì§€ë§‰ê¹Œì§€ ë‹¤ ì§€ë‚˜ê°„ ê²½ìš°
	}

	PRINTLOG(TEXT("TimeStampë¡œ ì´ë™: %d, NextEffectIndex: %d"), TimeStamp, NextEffectIndex);
}

void AMVE_StageLevel_EffectSequenceManager::UpdateTimeline(float DeltaTime)
{
	AccumulatedTime += DeltaTime;

	// 0.1ì´ˆ(1/10ì´ˆ)ë§ˆë‹¤ TimeStamp ì¦ê°€
	const float TimeStampInterval = 0.1f;

	while (AccumulatedTime >= TimeStampInterval)
	{
		AccumulatedTime -= TimeStampInterval;
		CurrentTimeStamp++;

		// í˜„ì¬ TimeStampì— í•´ë‹¹í•˜ëŠ” ì´í™íŠ¸ê°€ ìˆëŠ”ì§€ ì²´í¬
		while (NextEffectIndex < EffectSequenceDataArray.Num())
		{
			const FEffectSequenceData& EffectData = EffectSequenceDataArray[NextEffectIndex];

			if (EffectData.TimeStamp == CurrentTimeStamp)
			{
				// ì´í™íŠ¸ ì‹¤í–‰
				ExecuteEffectAtTimeStamp(EffectData);
				NextEffectIndex++;
			}
			else if (EffectData.TimeStamp > CurrentTimeStamp)
			{
				// ì•„ì§ ì‹œê°„ì´ ì•ˆ ë¨
				break;
			}
			else
			{
				// ì´ë¯¸ ì§€ë‚˜ê°„ ì´í™íŠ¸ (ê±´ë„ˆëœ€)
				NextEffectIndex++;
			}
		}
	}
}

void AMVE_StageLevel_EffectSequenceManager::ExecuteEffectAtTimeStamp(const FEffectSequenceData& Data)
{
	if (!Data.AssetID.IsValid())
	{
		PRINTLOG(TEXT("ìœ íš¨í•˜ì§€ ì•Šì€ AssetID"));
		return;
	}

	FString TagString = Data.AssetID.ToString();

	PRINTLOG(TEXT("ğŸ¬ Effect ì‹¤í–‰ - TimeStamp: %d, AssetID: %s"), Data.TimeStamp, *TagString);

	// GameplayTagë¥¼ íŒŒì‹±í•´ì„œ ì¹´í…Œê³ ë¦¬ í™•ì¸
	// ì˜ˆ: "VFX.Spotlight.FastSpeed" â†’ "VFX.Spotlight"
	// ì˜ˆ: "VFX.Flame.VeryFastSizeAndVeryFastSpeed" â†’ "VFX.Flame"
	// ì˜ˆ: "VFX.Fanfare.HighSpawnRate" â†’ "VFX.Fanfare"

	if (TagString.StartsWith(TEXT("VFX.Spotlight")))
	{
		// Spotlight ì´í™íŠ¸
		if (SpotlightManager)
		{
			int32 SequenceNumber = GetSpotlightSequenceNumber(Data.AssetID);
			if (SequenceNumber >= 0)
			{
				float DelayBetweenOrder = 0.0f; // ë™ì‹œ ì‹¤í–‰
				SpotlightManager->ExecuteSequenceNumber(SequenceNumber, DelayBetweenOrder);
				PRINTLOG(TEXT("âœ… SpotlightManager ì‹¤í–‰ - SequenceNumber: %d, AssetID: %s"), SequenceNumber, *TagString);
			}
			else
			{
				PRINTLOG(TEXT("âš ï¸ ìœ íš¨í•˜ì§€ ì•Šì€ Spotlight AssetID: %s"), *TagString);
			}
		}
		else
		{
			PRINTLOG(TEXT("âŒ SpotlightManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
		}
	}
	else if (TagString.StartsWith(TEXT("VFX.Flame")))
	{
		// Flame ì´í™íŠ¸
		if (FlameManager)
		{
			int32 SequenceNumber = GetFlameSequenceNumber(Data.AssetID);
			if (SequenceNumber >= 0)
			{
				float DelayBetweenOrder = 0.0f; // ë™ì‹œ ì‹¤í–‰
				FlameManager->ExecuteSequenceNumber(SequenceNumber, DelayBetweenOrder);
				PRINTLOG(TEXT("âœ… FlameManager ì‹¤í–‰ - SequenceNumber: %d, AssetID: %s"), SequenceNumber, *TagString);
			}
			else
			{
				PRINTLOG(TEXT("âš ï¸ ìœ íš¨í•˜ì§€ ì•Šì€ Flame AssetID: %s"), *TagString);
			}
		}
		else
		{
			PRINTLOG(TEXT("âŒ FlameManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
		}
	}
	else if (TagString.StartsWith(TEXT("VFX.Fanfare")))
	{
		// Fanfare ì´í™íŠ¸
		if (FanfareManager)
		{
			int32 SequenceNumber = GetFanfareSequenceNumber(Data.AssetID);
			if (SequenceNumber >= 0)
			{
				float DelayBetweenOrder = 0.0f; // ë™ì‹œ ì‹¤í–‰
				FanfareManager->ExecuteSequenceNumber(SequenceNumber, DelayBetweenOrder);
				PRINTLOG(TEXT("âœ… FanfareManager ì‹¤í–‰ - SequenceNumber: %d, AssetID: %s"), SequenceNumber, *TagString);
			}
			else
			{
				PRINTLOG(TEXT("âš ï¸ ìœ íš¨í•˜ì§€ ì•Šì€ Fanfare AssetID: %s"), *TagString);
			}
		}
		else
		{
			PRINTLOG(TEXT("âŒ FanfareManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
		}
	}
	else
	{
		PRINTLOG(TEXT("â“ ì•Œ ìˆ˜ ì—†ëŠ” ì¹´í…Œê³ ë¦¬ì˜ AssetID: %s"), *TagString);
	}
}

int32 AMVE_StageLevel_EffectSequenceManager::GetSpotlightSequenceNumber(const FGameplayTag& AssetID) const
{
	FString TagString = AssetID.ToString();

	// VFX.Spotlight.VerySlowSpeed â†’ 0
	if (TagString == TEXT("VFX.Spotlight.VerySlowSpeed"))
	{
		return 0;
	}
	// VFX.Spotlight.SlowSpeed â†’ 1
	else if (TagString == TEXT("VFX.Spotlight.SlowSpeed"))
	{
		return 1;
	}
	// VFX.Spotlight.NormalSpeed â†’ 2
	else if (TagString == TEXT("VFX.Spotlight.NormalSpeed"))
	{
		return 2;
	}
	// VFX.Spotlight.FastSpeed â†’ 3
	else if (TagString == TEXT("VFX.Spotlight.FastSpeed"))
	{
		return 3;
	}
	// VFX.Spotlight.VeryFastSpeed â†’ 4
	else if (TagString == TEXT("VFX.Spotlight.VeryFastSpeed"))
	{
		return 4;
	}
	else
	{
		// ë³€í™˜ ì‹¤íŒ¨
		return -1;
	}
}

int32 AMVE_StageLevel_EffectSequenceManager::GetFlameSequenceNumber(const FGameplayTag& AssetID) const
{
	FString TagString = AssetID.ToString();

	// VFX.Flame.VerySmallSizeAndVerySlowSpeed â†’ 0
	if (TagString == TEXT("VFX.Flame.VerySmallSizeAndVerySlowSpeed"))
	{
		return 0;
	}
	// VFX.Flame.SmallSizeAndSlowSpeed â†’ 1
	else if (TagString == TEXT("VFX.Flame.SmallSizeAndSlowSpeed"))
	{
		return 1;
	}
	// VFX.Flame.NormalSmallSizeAndNormalSpeed â†’ 2
	else if (TagString == TEXT("VFX.Flame.NormalSmallSizeAndNormalSpeed"))
	{
		return 2;
	}
	// VFX.Flame.FastSizeAndFastSpeed â†’ 3
	else if (TagString == TEXT("VFX.Flame.FastSizeAndFastSpeed"))
	{
		return 3;
	}
	// VFX.Flame.VeryFastSizeAndVeryFastSpeed â†’ 4
	else if (TagString == TEXT("VFX.Flame.VeryFastSizeAndVeryFastSpeed"))
	{
		return 4;
	}
	else
	{
		// ë³€í™˜ ì‹¤íŒ¨
		return -1;
	}
}

int32 AMVE_StageLevel_EffectSequenceManager::GetFanfareSequenceNumber(const FGameplayTag& AssetID) const
{
	FString TagString = AssetID.ToString();

	// VFX.Fanfare.VeryLowSpawnRate â†’ 0
	if (TagString == TEXT("VFX.Fanfare.VeryLowSpawnRate"))
	{
		return 0;
	}
	// VFX.Fanfare.LowSpawnRate â†’ 1
	else if (TagString == TEXT("VFX.Fanfare.LowSpawnRate"))
	{
		return 1;
	}
	// VFX.Fanfare.NormalSpawnRate â†’ 2
	else if (TagString == TEXT("VFX.Fanfare.NormalSpawnRate"))
	{
		return 2;
	}
	// VFX.Fanfare.HighSpawnRate â†’ 3
	else if (TagString == TEXT("VFX.Fanfare.HighSpawnRate"))
	{
		return 3;
	}
	// VFX.Fanfare.VeryHighSpawnRate â†’ 4
	else if (TagString == TEXT("VFX.Fanfare.VeryHighSpawnRate"))
	{
		return 4;
	}
	else
	{
		// ë³€í™˜ ì‹¤íŒ¨
		return -1;
	}
}

void AMVE_StageLevel_EffectSequenceManager::FindManagers()
{
	TArray<AActor*> FoundActors;

	// SpotlightManager ì°¾ê¸°
	UGameplayStatics::GetAllActorsOfClass(this, AMVE_StageLevel_SpotlightManager::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		SpotlightManager = Cast<AMVE_StageLevel_SpotlightManager>(FoundActors[0]);
		PRINTLOG(TEXT("âœ… SpotlightManager ì°¾ìŒ"));
	}
	else
	{
		PRINTLOG(TEXT("âš ï¸ SpotlightManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
	}

	// FlameManager ì°¾ê¸°
	FoundActors.Empty();
	UGameplayStatics::GetAllActorsOfClass(this, AMVE_StageLevel_FlameManager::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		FlameManager = Cast<AMVE_StageLevel_FlameManager>(FoundActors[0]);
		PRINTLOG(TEXT("âœ… FlameManager ì°¾ìŒ"));
	}
	else
	{
		PRINTLOG(TEXT("âš ï¸ FlameManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
	}

	// FanfareManager ì°¾ê¸°
	FoundActors.Empty();
	UGameplayStatics::GetAllActorsOfClass(this, AMVE_StageLevel_FanfareManager::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		FanfareManager = Cast<AMVE_StageLevel_FanfareManager>(FoundActors[0]);
		PRINTLOG(TEXT("âœ… FanfareManager ì°¾ìŒ"));
	}
	else
	{
		PRINTLOG(TEXT("âš ï¸ FanfareManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
	}
}
