
#include "../Public/MVE_STD_WidgetClass_FinalCheckSettings.h"

#include "MVE_API_Helper.h"
#include "MVE_AUD_WidgetClass_ConcertRoom.h"
#include "MVE_GIS_SessionManager.h"
#include "MVE_STD_WC_PlaylistBuilder.h"
#include "MVE_STU_WC_EffectSequencePreview.h"
#include "MVE_StageLevel_EffectSequenceManager.h"
#include "MVE_STU_StagePreviewCaptureActor.h"
#include "UIManagerSubsystem.h"
#include "Components/Button.h"
#include "Components/EditableTextBox.h"
#include "Data/RoomInfo.h"
#include "Kismet/GameplayStatics.h"
#include "MVE.h"

void UMVE_STD_WidgetClass_FinalCheckSettings::NativeConstruct()
{
	Super::NativeConstruct();

	if (StartConcertButton)
		StartConcertButton.Get()->OnClicked.AddDynamic(this, &UMVE_STD_WidgetClass_FinalCheckSettings::OnStartConcertButtonClicked);

	if (PlaylistBuilderWidget)
		PlaylistBuilderWidget.Get()->OnAudioFileSelected.AddDynamic(this, &UMVE_STD_WidgetClass_FinalCheckSettings::OnAudioFileSelected);

	// EffectSequenceManager ì°¾ê¸° (PlaylistBuilderì™€ EffectSequencePreviewì— ê³µí†µ ì„¤ì •)
	AMVE_StageLevel_EffectSequenceManager* Manager = nullptr;
	TArray<AActor*> FoundActors;
	UGameplayStatics::GetAllActorsOfClass(this, AMVE_StageLevel_EffectSequenceManager::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		Manager = Cast<AMVE_StageLevel_EffectSequenceManager>(FoundActors[0]);
		if (Manager)
		{
			PRINTLOG(TEXT("EffectSequenceManager ì°¾ê¸° ì„±ê³µ"));
		}
	}
	else
	{
		PRINTLOG(TEXT("EffectSequenceManagerë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤. PreviewStageLevelì— ë°°ì¹˜ë˜ì–´ ìˆëŠ”ì§€ í™•ì¸í•˜ì„¸ìš”."));
	}

	// PlaylistBuilderì— EffectSequenceManager ì„¤ì •
	if (PlaylistBuilderWidget && Manager)
	{
		PlaylistBuilderWidget->SetEffectSequenceManager(Manager);
		PRINTLOG(TEXT("PlaylistBuilderì— EffectSequenceManager ì„¤ì • ì™„ë£Œ"));
	}

	// EffectSequencePreview ì„¤ì •
	if (EffectSequencePreviewWidget)
	{
		// EffectSequenceManager ì„¤ì •
		if (Manager)
		{
			EffectSequencePreviewWidget->SetEffectSequenceManager(Manager);
			PRINTLOG(TEXT("EffectSequencePreviewì— EffectSequenceManager ì„¤ì • ì™„ë£Œ"));
		}

		// StagePreviewCaptureActor ì°¾ê¸°
		FoundActors.Empty();
		UGameplayStatics::GetAllActorsOfClass(this, AMVE_STU_StagePreviewCaptureActor::StaticClass(), FoundActors);

		if (FoundActors.Num() > 0)
		{
			AMVE_STU_StagePreviewCaptureActor* CaptureActor = Cast<AMVE_STU_StagePreviewCaptureActor>(FoundActors[0]);
			if (CaptureActor && CaptureActor->RenderTarget)
			{
				// SceneCaptureComponentê°€ RenderTargetì— ìº¡ì²˜í•˜ë„ë¡ ì„¤ì •
				CaptureActor->SetRenderTarget(CaptureActor->RenderTarget);

				// ìœ„ì ¯ì— RenderTarget ì „ë‹¬
				EffectSequencePreviewWidget->SetRenderTarget(CaptureActor->RenderTarget);
				PRINTLOG(TEXT("StagePreviewCaptureActor RenderTarget ì„¤ì • ì™„ë£Œ"));
			}
		}
		else
		{
			PRINTLOG(TEXT("StagePreviewCaptureActorë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤. PreviewStageLevelì— ë°°ì¹˜ë˜ì–´ ìˆëŠ”ì§€ í™•ì¸í•˜ì„¸ìš”."));
		}
	}
}

void UMVE_STD_WidgetClass_FinalCheckSettings::OnStartConcertButtonClicked()
{
	PlaylistBuilderWidget->SavePlaylistToSessionManager();
	
	FConcertInfo ConcertInfo;
	ConcertInfo.ConcertName = RoomTitleEditableText->GetText().ToString();
	ConcertInfo.MaxAudience = 20;
	ConcertInfo.Songs = TArray<FConcertSong>();
	ConcertInfo.Accessories = TArray<FAccessory>();

	if (UMVE_GIS_SessionManager* SessionManager = GetGameInstance()->GetSubsystem<UMVE_GIS_SessionManager>())
	{
		SessionManager->CreateSession(ConcertInfo);
	}
}

void UMVE_STD_WidgetClass_FinalCheckSettings::OnAudioFileSelected(const FAudioFile& SelectedAudio)
{
	EffectSequencePreviewWidget->SetAudioFile(SelectedAudio);

	// TestMode ì²´í¬
	if (EffectSequencePreviewWidget->bTestMode)
	{
		// ğŸ§ª í…ŒìŠ¤íŠ¸ ëª¨ë“œ: ë”ë¯¸ ë°ì´í„°ë¡œ EffectSequenceManager ë™ì‘ í™•ì¸
		EffectSequencePreviewWidget->LoadTestData();
		PRINTLOG(TEXT("âœ… TestMode í™œì„±í™” - ë”ë¯¸ ë°ì´í„° ë¡œë“œ"));
	}
	else
	{
		// ğŸ¯ ì‹¤ì œ ëª¨ë“œ: AI ì„œë²„ì— ë©”íƒ€ë°ì´í„° ì „ì†¡
		// TODO: AI ì„œë²„ì™€ í†µì‹ í•˜ì—¬ TimeStamp ë¶„ì„ ê²°ê³¼ ë°›ê¸°
		// ì˜ˆì‹œ:
		// FString Title = SelectedAudio.Title;
		// FString Artist = SelectedAudio.Artist;
		// AI_Client->AnalyzeMusicMetadata(Title, Artist, [this](const TArray<FEffectSequenceData>& SequenceData, int32 TotalDuration)
		// {
		//     EffectSequencePreviewWidget->SetSequenceData(SequenceData, TotalDuration);
		// });

		PRINTLOG(TEXT("âš ï¸ TestMode ë¹„í™œì„±í™” - AI ì„œë²„ í†µì‹ ì€ ì•„ì§ êµ¬í˜„ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤"));
	}
}
